In [1]:
import torch
import numpy as np
# import torchvision

In [43]:
x = torch.rand(4, 4, 4)
x

tensor([[[2.9559e-01, 2.3243e-02, 7.0514e-01, 9.3393e-01],
         [9.9871e-01, 4.4064e-01, 2.4428e-01, 8.9414e-01],
         [1.1364e-02, 5.0886e-01, 4.9039e-02, 5.5310e-01],
         [5.4242e-01, 1.0928e-01, 1.4123e-01, 1.4126e-01]],

        [[3.8294e-01, 2.0907e-01, 3.4937e-01, 8.1889e-01],
         [7.2637e-01, 7.3630e-01, 9.6844e-01, 4.7789e-01],
         [7.6362e-01, 2.8382e-02, 6.9849e-01, 4.0299e-01],
         [5.2648e-01, 5.4138e-01, 7.7825e-01, 6.8973e-01]],

        [[5.5953e-01, 9.1607e-01, 5.6896e-02, 6.1181e-02],
         [4.2002e-01, 1.2508e-01, 5.4027e-01, 9.2248e-01],
         [1.1958e-01, 1.4655e-01, 9.2713e-01, 5.7142e-01],
         [9.8790e-01, 8.9525e-01, 3.3487e-01, 3.0359e-01]],

        [[7.2152e-01, 5.4377e-04, 5.4544e-01, 9.9347e-01],
         [5.6449e-01, 6.3624e-01, 6.1294e-01, 9.5716e-01],
         [4.0855e-01, 3.7573e-01, 2.0014e-01, 6.9019e-01],
         [9.2959e-01, 3.1986e-01, 5.4154e-02, 3.7457e-01]]])

In [44]:
x.adjoint()

tensor([[[2.9559e-01, 9.9871e-01, 1.1364e-02, 5.4242e-01],
         [2.3243e-02, 4.4064e-01, 5.0886e-01, 1.0928e-01],
         [7.0514e-01, 2.4428e-01, 4.9039e-02, 1.4123e-01],
         [9.3393e-01, 8.9414e-01, 5.5310e-01, 1.4126e-01]],

        [[3.8294e-01, 7.2637e-01, 7.6362e-01, 5.2648e-01],
         [2.0907e-01, 7.3630e-01, 2.8382e-02, 5.4138e-01],
         [3.4937e-01, 9.6844e-01, 6.9849e-01, 7.7825e-01],
         [8.1889e-01, 4.7789e-01, 4.0299e-01, 6.8973e-01]],

        [[5.5953e-01, 4.2002e-01, 1.1958e-01, 9.8790e-01],
         [9.1607e-01, 1.2508e-01, 1.4655e-01, 8.9525e-01],
         [5.6896e-02, 5.4027e-01, 9.2713e-01, 3.3487e-01],
         [6.1181e-02, 9.2248e-01, 5.7142e-01, 3.0359e-01]],

        [[7.2152e-01, 5.6449e-01, 4.0855e-01, 9.2959e-01],
         [5.4377e-04, 6.3624e-01, 3.7573e-01, 3.1986e-01],
         [5.4544e-01, 6.1294e-01, 2.0014e-01, 5.4154e-02],
         [9.9347e-01, 9.5716e-01, 6.9019e-01, 3.7457e-01]]])

In [46]:
# (x.adjoint() / x.det()) @ x
torch.dstack([x, x.adjoint()])
# stack creates new dimension (ups rank)
# hstack makes more rows
# dstack makes more columns
# vstack makes more of the other thing

tensor([[[2.9559e-01, 2.3243e-02, 7.0514e-01, 9.3393e-01, 2.9559e-01,
          9.9871e-01, 1.1364e-02, 5.4242e-01],
         [9.9871e-01, 4.4064e-01, 2.4428e-01, 8.9414e-01, 2.3243e-02,
          4.4064e-01, 5.0886e-01, 1.0928e-01],
         [1.1364e-02, 5.0886e-01, 4.9039e-02, 5.5310e-01, 7.0514e-01,
          2.4428e-01, 4.9039e-02, 1.4123e-01],
         [5.4242e-01, 1.0928e-01, 1.4123e-01, 1.4126e-01, 9.3393e-01,
          8.9414e-01, 5.5310e-01, 1.4126e-01]],

        [[3.8294e-01, 2.0907e-01, 3.4937e-01, 8.1889e-01, 3.8294e-01,
          7.2637e-01, 7.6362e-01, 5.2648e-01],
         [7.2637e-01, 7.3630e-01, 9.6844e-01, 4.7789e-01, 2.0907e-01,
          7.3630e-01, 2.8382e-02, 5.4138e-01],
         [7.6362e-01, 2.8382e-02, 6.9849e-01, 4.0299e-01, 3.4937e-01,
          9.6844e-01, 6.9849e-01, 7.7825e-01],
         [5.2648e-01, 5.4138e-01, 7.7825e-01, 6.8973e-01, 8.1889e-01,
          4.7789e-01, 4.0299e-01, 6.8973e-01]],

        [[5.5953e-01, 9.1607e-01, 5.6896e-02, 6.1181e-02, 5.

In [53]:
torch.cat([x[1:], x[1:].adjoint()])

tensor([[[3.8294e-01, 2.0907e-01, 3.4937e-01, 8.1889e-01],
         [7.2637e-01, 7.3630e-01, 9.6844e-01, 4.7789e-01],
         [7.6362e-01, 2.8382e-02, 6.9849e-01, 4.0299e-01],
         [5.2648e-01, 5.4138e-01, 7.7825e-01, 6.8973e-01]],

        [[5.5953e-01, 9.1607e-01, 5.6896e-02, 6.1181e-02],
         [4.2002e-01, 1.2508e-01, 5.4027e-01, 9.2248e-01],
         [1.1958e-01, 1.4655e-01, 9.2713e-01, 5.7142e-01],
         [9.8790e-01, 8.9525e-01, 3.3487e-01, 3.0359e-01]],

        [[7.2152e-01, 5.4377e-04, 5.4544e-01, 9.9347e-01],
         [5.6449e-01, 6.3624e-01, 6.1294e-01, 9.5716e-01],
         [4.0855e-01, 3.7573e-01, 2.0014e-01, 6.9019e-01],
         [9.2959e-01, 3.1986e-01, 5.4154e-02, 3.7457e-01]],

        [[3.8294e-01, 7.2637e-01, 7.6362e-01, 5.2648e-01],
         [2.0907e-01, 7.3630e-01, 2.8382e-02, 5.4138e-01],
         [3.4937e-01, 9.6844e-01, 6.9849e-01, 7.7825e-01],
         [8.1889e-01, 4.7789e-01, 4.0299e-01, 6.8973e-01]],

        [[5.5953e-01, 4.2002e-01, 1.1958e-01, 9.

In [51]:
x.tensor_split([1, 2, 3], dim=1)
# partitions tensor along given dimension

(tensor([[[2.9559e-01, 2.3243e-02, 7.0514e-01, 9.3393e-01]],
 
         [[3.8294e-01, 2.0907e-01, 3.4937e-01, 8.1889e-01]],
 
         [[5.5953e-01, 9.1607e-01, 5.6896e-02, 6.1181e-02]],
 
         [[7.2152e-01, 5.4377e-04, 5.4544e-01, 9.9347e-01]]]),
 tensor([[[0.9987, 0.4406, 0.2443, 0.8941]],
 
         [[0.7264, 0.7363, 0.9684, 0.4779]],
 
         [[0.4200, 0.1251, 0.5403, 0.9225]],
 
         [[0.5645, 0.6362, 0.6129, 0.9572]]]),
 tensor([[[0.0114, 0.5089, 0.0490, 0.5531]],
 
         [[0.7636, 0.0284, 0.6985, 0.4030]],
 
         [[0.1196, 0.1465, 0.9271, 0.5714]],
 
         [[0.4085, 0.3757, 0.2001, 0.6902]]]),
 tensor([[[0.5424, 0.1093, 0.1412, 0.1413]],
 
         [[0.5265, 0.5414, 0.7783, 0.6897]],
 
         [[0.9879, 0.8953, 0.3349, 0.3036]],
 
         [[0.9296, 0.3199, 0.0542, 0.3746]]]))

In [58]:
x[1:, 1:, 1:]

tensor([[[0.7363, 0.9684, 0.4779],
         [0.0284, 0.6985, 0.4030],
         [0.5414, 0.7783, 0.6897]],

        [[0.1251, 0.5403, 0.9225],
         [0.1465, 0.9271, 0.5714],
         [0.8953, 0.3349, 0.3036]],

        [[0.6362, 0.6129, 0.9572],
         [0.3757, 0.2001, 0.6902],
         [0.3199, 0.0542, 0.3746]]])

In [59]:
x + 5

tensor([[[5.2956, 5.0232, 5.7051, 5.9339],
         [5.9987, 5.4406, 5.2443, 5.8941],
         [5.0114, 5.5089, 5.0490, 5.5531],
         [5.5424, 5.1093, 5.1412, 5.1413]],

        [[5.3829, 5.2091, 5.3494, 5.8189],
         [5.7264, 5.7363, 5.9684, 5.4779],
         [5.7636, 5.0284, 5.6985, 5.4030],
         [5.5265, 5.5414, 5.7783, 5.6897]],

        [[5.5595, 5.9161, 5.0569, 5.0612],
         [5.4200, 5.1251, 5.5403, 5.9225],
         [5.1196, 5.1465, 5.9271, 5.5714],
         [5.9879, 5.8953, 5.3349, 5.3036]],

        [[5.7215, 5.0005, 5.5454, 5.9935],
         [5.5645, 5.6362, 5.6129, 5.9572],
         [5.4085, 5.3757, 5.2001, 5.6902],
         [5.9296, 5.3199, 5.0542, 5.3746]]])